using System.Diagnostics; using System.Globalization; using System.IO; using System.Windows; using System.Windows.Input; using System.Windows.Media; using System.Windows.Media.Imaging; using System.Windows.Threading;
using FractalExplorerWPF.Core.Rendering; using FractalExplorerWPF.Infrastructure; using FractalExplorerWPF.Models; using Microsoft.Win32; using Point=System.Windows.Point;
namespace FractalExplorerWPF.Views;
public partial class BuddhabrotWindow:Window
{
    private readonly DispatcherTimer _timer=new(){Interval=TimeSpan.FromMilliseconds(350)}; private readonly BuddhabrotPaletteManager _palettes=new(); private readonly BuddhabrotSaveStore _saves=new();
    private readonly TransformGroup _transform=new(); private readonly ScaleTransform _scale=new(1,1); private readonly TranslateTransform _translation=new();
    private CancellationTokenSource? _cts; private bool _rendering,_panning,_controls=true,_fullscreen,_hasFrame; private Point _panStart; private decimal _centerX,_centerY,_zoom=1,_renderedCenterX,_renderedCenterY,_renderedZoom=1; private WindowStyle _oldStyle;private WindowState _oldState;
    public BuddhabrotWindow(){InitializeComponent();_transform.Children.Add(_scale);_transform.Children.Add(_translation);StableImage.RenderTransformOrigin=new Point(.5,.5);StableImage.RenderTransform=_transform;
        ModeBox.SelectedIndex=0;SamplesBox.Text="250000";IterationsBox.Text="500";ZoomBox.Text="1";MinReBox.Text="-2";MaxReBox.Text="1";MinImBox.Text="-1.5";MaxImBox.Text="1.5";
        ThreadsBox.Items.Add("Auto");for(int i=1;i<=Environment.ProcessorCount;i++)ThreadsBox.Items.Add(i);ThreadsBox.SelectedIndex=0;_timer.Tick+=(_,_)=>{_timer.Stop();_ = RenderAsync();};Loaded+=(_,_)=>Schedule();}
    public BuddhabrotState CaptureState(string name){if(!int.TryParse(SamplesBox.Text,out int samples)||samples<1000)throw new InvalidOperationException("Сэмплов должно быть не меньше 1000.");if(!int.TryParse(IterationsBox.Text,out int iterations)||iterations is<10 or>10000)throw new InvalidOperationException("Итерации должны быть от 10 до 10000.");
        if(!Read(MinReBox.Text,out decimal minRe)||!Read(MaxReBox.Text,out decimal maxRe)||!Read(MinImBox.Text,out decimal minIm)||!Read(MaxImBox.Text,out decimal maxIm)||minRe>=maxRe||minIm>=maxIm)throw new InvalidOperationException("Проверьте границы области выборки.");
        return new BuddhabrotState{SaveName=name,Timestamp=DateTime.Now,CenterX=_centerX,CenterY=_centerY,Zoom=_zoom,SampleCount=samples,MaxIterations=iterations,RenderMode=(BuddhabrotRenderMode)Math.Clamp(ModeBox.SelectedIndex,0,2),SampleMinRe=minRe,SampleMaxRe=maxRe,SampleMinIm=minIm,SampleMaxIm=maxIm,Palette=_palettes.ActivePalette.Clone(_palettes.ActivePalette.Name,_palettes.ActivePalette.IsBuiltIn)};}
    public void LoadState(BuddhabrotState s){_cts?.Cancel();_centerX=s.CenterX;_centerY=s.CenterY;_zoom=s.Zoom;SamplesBox.Text=s.SampleCount.ToString();IterationsBox.Text=s.MaxIterations.ToString();ModeBox.SelectedIndex=(int)s.RenderMode;MinReBox.Text=F(s.SampleMinRe);MaxReBox.Text=F(s.SampleMaxRe);MinImBox.Text=F(s.SampleMinIm);MaxImBox.Text=F(s.SampleMaxIm);ZoomBox.Text=F(_zoom);var p=_palettes.Palettes.FirstOrDefault(x=>x.Name==s.Palette.Name);if(p is null){p=s.Palette.Clone(s.Palette.Name);_palettes.Palettes.Add(p);}_palettes.ActivePalette=p;UpdateTransform();Schedule();}
    public async Task<BitmapSource> RenderStatePreviewAsync(BuddhabrotState state,int width,int height,CancellationToken token){state.SampleCount=Math.Max(25000,state.SampleCount/6);return await RenderBitmapAsync(state,width,height,token,null);}
    private void Parameter_OnChanged(object s,EventArgs e)=>Schedule();private void ZoomBox_OnChanged(object s,System.Windows.Controls.TextChangedEventArgs e){if(Read(ZoomBox.Text,out decimal z)){_zoom=Math.Clamp(z,.0000001m,100000m);UpdateTransform();Schedule();}}
    private void Schedule(){if(!IsLoaded)return;_cts?.Cancel();_timer.Stop();_timer.Start();} private void Render_OnClick(object s,RoutedEventArgs e){_timer.Stop();_cts?.Cancel();_ = RenderAsync();}private void Cancel_OnClick(object s,RoutedEventArgs e)=>_cts?.Cancel();
    private async Task RenderAsync(){if(_rendering){Schedule();return;}BuddhabrotState state;try{state=CaptureState("preview");}catch(Exception ex){StatusText.Text=ex.Message;return;}_cts?.Dispose();_cts=new CancellationTokenSource();CancellationToken token=_cts.Token;_rendering=true;CancelButton.IsEnabled=true;AccumulationBadge.Visibility=Visibility.Visible;var watch=Stopwatch.StartNew();
        try{DpiScale dpi=VisualTreeHelper.GetDpi(CanvasHost);int width=Math.Max(1,(int)Math.Ceiling(CanvasHost.ActualWidth*dpi.DpiScaleX)),height=Math.Max(1,(int)Math.Ceiling(CanvasHost.ActualHeight*dpi.DpiScaleY));var bitmap=new WriteableBitmap(width,height,dpi.PixelsPerInchX,dpi.PixelsPerInchY,PixelFormats.Bgra32,null);CurrentImage.Source=bitmap;var renderer=new BuddhabrotRenderer(state,width,height,Threads());int batch=Math.Clamp(state.SampleCount/40,5000,100000),last=0;
            while(renderer.ProcessedSamples<state.SampleCount){token.ThrowIfCancellationRequested();var sw=Stopwatch.StartNew();await Task.Run(()=>renderer.Accumulate(batch,token),token);sw.Stop();int processed=renderer.ProcessedSamples,percent=(int)(processed*100d/state.SampleCount);ProgressBar.Value=percent;ProgressText.Text=$"Накопление орбит: {percent}%";AccumulationText.Text=$"{processed:N0} / {state.SampleCount:N0} сэмплов";
                bool present=processed==state.SampleCount||processed-last>=Math.Max(2500,state.SampleCount/24);if(present){byte[] frame=await Task.Run(renderer.CreateFrame,token);bitmap.WritePixels(new Int32Rect(0,0,width,height),frame,width*4,0);last=processed;}
                batch=sw.ElapsedMilliseconds<45?Math.Min(400000,(int)(batch*1.5)):sw.ElapsedMilliseconds>140?Math.Max(5000,(int)(batch*.7)):batch;}
            BitmapSource done=bitmap.Clone();done.Freeze();StableImage.Source=done;CurrentImage.Source=null;_renderedCenterX=state.CenterX;_renderedCenterY=state.CenterY;_renderedZoom=state.Zoom;_hasFrame=true;UpdateTransform();StatusText.Text=$"Готово за {watch.Elapsed.TotalSeconds:F3} сек.";ProgressText.Text="Накопление завершено";ProgressBar.Value=100;}
        catch(OperationCanceledException){CurrentImage.Source=null;StatusText.Text="Рендер отменён";}catch(Exception ex){CurrentImage.Source=null;MessageBox.Show(this,ex.Message,"Буддаброт",MessageBoxButton.OK,MessageBoxImage.Error);}finally{_rendering=false;CancelButton.IsEnabled=false;AccumulationBadge.Visibility=Visibility.Collapsed;}}
    private int Threads()=>ThreadsBox.SelectedItem?.ToString()=="Auto"?Environment.ProcessorCount:Convert.ToInt32(ThreadsBox.SelectedItem);
    private void Palette_OnClick(object s,RoutedEventArgs e){var w=new BuddhabrotPaletteWindow(_palettes){Owner=this};w.PaletteApplied+=(_,_)=>Schedule();w.ShowDialog();}
    private void Saves_OnClick(object s,RoutedEventArgs e)=>new BuddhabrotSavesWindow(this,_saves){Owner=this}.ShowDialog();
    private async void Export_OnClick(object s,RoutedEventArgs e){DpiScale dpi=VisualTreeHelper.GetDpi(CanvasHost);var options=new MandelbrotExportWindow{Owner=this,ExportWidth=Math.Max(1,(int)Math.Ceiling(CanvasHost.ActualWidth*dpi.DpiScaleX)),ExportHeight=Math.Max(1,(int)Math.Ceiling(CanvasHost.ActualHeight*dpi.DpiScaleY))};if(options.ShowDialog()!=true)return;string ext=options.ExportFormat switch{MandelbrotExportFormat.Jpeg=>"jpg",MandelbrotExportFormat.Bmp=>"bmp",_=>"png"};var file=new SaveFileDialog{FileName=$"buddhabrot_{DateTime.Now:yyyyMMdd_HHmmss}.{ext}",Filter=options.ExportFormat switch{MandelbrotExportFormat.Jpeg=>"JPEG|*.jpg",MandelbrotExportFormat.Bmp=>"Bitmap|*.bmp",_=>"PNG|*.png"}};if(file.ShowDialog(this)!=true)return;
        _cts?.Cancel();_cts?.Dispose();_cts=new CancellationTokenSource();try{BuddhabrotState state=CaptureState("export");BitmapSource image=await RenderBitmapAsync(state,options.ExportWidth,options.ExportHeight,_cts.Token,new Progress<int>(p=>{ProgressBar.Value=p;ProgressText.Text=$"Экспорт: {p}%";}));BitmapEncoder encoder=options.ExportFormat switch{MandelbrotExportFormat.Jpeg=>new JpegBitmapEncoder{QualityLevel=options.JpegQuality},MandelbrotExportFormat.Bmp=>new BmpBitmapEncoder(),_=>new PngBitmapEncoder()};encoder.Frames.Add(BitmapFrame.Create(image));await using FileStream stream=File.Create(file.FileName);encoder.Save(stream);StatusText.Text=$"Сохранено: {file.FileName}";}catch(OperationCanceledException){StatusText.Text="Экспорт отменён";}}
    private async Task<BitmapSource> RenderBitmapAsync(BuddhabrotState state,int width,int height,CancellationToken token,IProgress<int>? progress){var renderer=new BuddhabrotRenderer(state,width,height,Threads());while(renderer.ProcessedSamples<state.SampleCount){await Task.Run(()=>renderer.Accumulate(Math.Min(100000,state.SampleCount-renderer.ProcessedSamples),token),token);progress?.Report((int)(renderer.ProcessedSamples*100d/state.SampleCount));}byte[] pixels=await Task.Run(renderer.CreateFrame,token);BitmapSource b=BitmapSource.Create(width,height,96,96,PixelFormats.Bgra32,null,pixels,width*4);b.Freeze();return b;}
    private void CanvasHost_OnSizeChanged(object s,SizeChangedEventArgs e){UpdateTransform();Schedule();}private void CanvasHost_OnMouseWheel(object s,MouseWheelEventArgs e){Point p=e.GetPosition(CanvasHost);var before=ScreenToWorld(p);_zoom=Math.Clamp(_zoom*(e.Delta>0?1.25m:.8m),.0000001m,100000m);var after=ScreenToWorld(p);_centerX+=before.Real-after.Real;_centerY+=before.Imaginary-after.Imaginary;UpdateTransform();ZoomBox.Text=F(_zoom);Schedule();}
    private void CanvasHost_OnMouseLeftButtonDown(object s,MouseButtonEventArgs e){_panning=true;_panStart=e.GetPosition(CanvasHost);CanvasHost.CaptureMouse();}private void CanvasHost_OnMouseMove(object s,MouseEventArgs e){if(!_panning)return;Point p=e.GetPosition(CanvasHost);var a=ScreenToWorld(_panStart);var b=ScreenToWorld(p);_centerX+=a.Real-b.Real;_centerY+=a.Imaginary-b.Imaginary;_panStart=p;UpdateTransform();}private void CanvasHost_OnMouseLeftButtonUp(object s,MouseButtonEventArgs e){if(!_panning)return;_panning=false;CanvasHost.ReleaseMouseCapture();Schedule();}
    private (decimal Real,decimal Imaginary) ScreenToWorld(Point p){decimal sx=4m/_zoom,sy=sx*(decimal)Math.Max(1,CanvasHost.ActualHeight)/(decimal)Math.Max(1,CanvasHost.ActualWidth);return(_centerX+((decimal)p.Y-(decimal)CanvasHost.ActualHeight/2)*sy/(decimal)Math.Max(1,CanvasHost.ActualHeight),_centerY+((decimal)p.X-(decimal)CanvasHost.ActualWidth/2)*sx/(decimal)Math.Max(1,CanvasHost.ActualWidth));}
    private void UpdateTransform(){if(!_hasFrame||CanvasHost.ActualWidth<=0)return;double ratio=(double)(_zoom/_renderedZoom),w=CanvasHost.ActualWidth,h=CanvasHost.ActualHeight;decimal sx=4m/_zoom,sy=sx*(decimal)h/(decimal)w;_scale.ScaleX=_scale.ScaleY=ratio;_translation.X=(double)((_renderedCenterY-_centerY)/sx)*w;_translation.Y=(double)((_renderedCenterX-_centerX)/sy)*h;}
    private void Toggle_OnClick(object s,RoutedEventArgs e){_controls=!_controls;ControlsColumn.Width=_controls?new GridLength(300):new GridLength(0);ControlsHost.Visibility=_controls?Visibility.Visible:Visibility.Collapsed;ToggleButton.Content=_controls?"✕":"☰";Schedule();}private void Window_OnKeyDown(object s,KeyEventArgs e){if(e.Key==Key.F11||e.Key==Key.Escape&&_fullscreen)ToggleFull();}private void ToggleFull(){if(!_fullscreen){_oldStyle=WindowStyle;_oldState=WindowState;WindowStyle=WindowStyle.None;WindowState=WindowState.Maximized;}else{WindowStyle=_oldStyle;WindowState=_oldState;}_fullscreen=!_fullscreen;}
    private void Window_OnClosing(object? s,System.ComponentModel.CancelEventArgs e){_timer.Stop();_cts?.Cancel();_cts?.Dispose();}private static bool Read(string t,out decimal v)=>decimal.TryParse(t,NumberStyles.Float,CultureInfo.InvariantCulture,out v)||decimal.TryParse(t,NumberStyles.Float,CultureInfo.CurrentCulture,out v);private static string F(decimal v)=>v.ToString("G15",CultureInfo.InvariantCulture);
}
