using System.Diagnostics;using System.Globalization;using System.IO;using System.Windows;using System.Windows.Input;using System.Windows.Media;using System.Windows.Media.Imaging;using System.Windows.Threading;using FractalExplorerWPF.Controls;using FractalExplorerWPF.Core.Rendering;using FractalExplorerWPF.Infrastructure;using FractalExplorerWPF.Infrastructure.ColorPicking;using FractalExplorerWPF.Models;using Microsoft.Win32;using Color=System.Windows.Media.Color;using Point=System.Windows.Point;
namespace FractalExplorerWPF.Views;
public partial class IfsWindow:Window
{
    private readonly DispatcherTimer _timer=new(){Interval=TimeSpan.FromMilliseconds(260)};private readonly IfsSaveStore _saves=new();private readonly ColorSelectionService _picker=ColorSelectionService.Default;private readonly List<IfsAffineTransform> _transforms=[];private readonly TransformGroup _transform=new();private readonly ScaleTransform _imageScale=new(1,1);private readonly TranslateTransform _translation=new();
    private CancellationTokenSource? _cts;private bool _rendering,_panning,_controls=true,_fullscreen,_hasFrame,_syncing;private Point _panStart;private double _centerX,_centerY,_scale=5,_renderedCenterX,_renderedCenterY,_renderedScale=5;private Color _fractalColor=Colors.Lime,_backgroundColor=Colors.Black;private string? _presetId;private WindowStyle _oldStyle;private WindowState _oldState;
    public IfsWindow(){InitializeComponent();_transform.Children.Add(_imageScale);_transform.Children.Add(_translation);StableImage.RenderTransformOrigin=new Point(.5,.5);StableImage.RenderTransform=_transform;PresetBox.ItemsSource=IfsPresets.All;ApplyPreset(IfsPresets.All[0]);UpdateSwatches();_timer.Tick+=(_,_)=>{_timer.Stop();_=RenderAsync();};Loaded+=(_,_)=>Schedule();}
    public IfsState CaptureState(string name){if(!int.TryParse(IterationsBox.Text,out int iterations)||iterations is<10000 or>10000000)throw new InvalidOperationException("Итерации должны быть от 10 000 до 10 000 000.");if(!Read(CenterXBox.Text,out double x)||!Read(CenterYBox.Text,out double y)||!Read(ScaleBox.Text,out double scale)||scale is<.05 or>40)throw new InvalidOperationException("Проверьте центр и масштаб (0.05–40).");if(_transforms.Count==0)throw new InvalidOperationException("Добавьте хотя бы одно преобразование.");return new(){SaveName=name,Timestamp=DateTime.Now,PointOfInterestId=_presetId,Iterations=iterations,CenterX=x,CenterY=y,Scale=scale,Transforms=_transforms.Select(t=>t.Clone()).ToList(),FractalColor=_fractalColor,BackgroundColor=_backgroundColor};}
    public void LoadState(IfsState s){_cts?.Cancel();_syncing=true;try{_presetId=s.PointOfInterestId;_centerX=s.CenterX;_centerY=s.CenterY;_scale=s.Scale<=0?2.4:s.Scale;IterationsBox.Text=s.Iterations.ToString();CenterXBox.Text=F(_centerX);CenterYBox.Text=F(_centerY);ScaleBox.Text=F(_scale);_transforms.Clear();if(s.Transforms.Count>0)_transforms.AddRange(s.Transforms.Select(t=>t.Clone()));else if(IfsPresets.All.FirstOrDefault(p=>p.Id==s.PointOfInterestId)is{} preset)_transforms.AddRange(preset.Transforms.Select(t=>t.Clone()));_fractalColor=s.FractalColor;_backgroundColor=s.BackgroundColor;PresetBox.SelectedItem=IfsPresets.All.FirstOrDefault(p=>p.Id==_presetId);}finally{_syncing=false;}UpdateSwatches();UpdateTransform();Schedule();}
    public BitmapSource? CaptureCurrentPreview(int width, int height) =>
        SavePreviewCapture.Capture(SavePreviewLayer, CanvasHost.Background, width, height, StableImage, CurrentImage);

    public Task<BitmapSource> RenderStatePreviewAsync(
        IfsState state, int width, int height, CancellationToken token, IProgress<int>? progress = null) =>
        RenderBitmapAsync(state.Clone(), width, height, token, progress);
    private void ApplyPreset(IfsPreset p){_syncing=true;try{_presetId=p.Id;_centerX=p.CenterX;_centerY=p.CenterY;_scale=p.Scale;IterationsBox.Text=p.Iterations.ToString();CenterXBox.Text=F(_centerX);CenterYBox.Text=F(_centerY);ScaleBox.Text=F(_scale);_transforms.Clear();_transforms.AddRange(p.Transforms.Select(t=>t.Clone()));PresetBox.SelectedItem=p;}finally{_syncing=false;}UpdateTransform();}
    private void Preset_OnChanged(object sender,System.Windows.Controls.SelectionChangedEventArgs e){if(_syncing||PresetBox.SelectedItem is not IfsPreset p)return;ApplyPreset(p);Schedule();}
    private void Parameter_OnChanged(object sender,EventArgs e){if(!_syncing)Schedule();}private void Viewport_OnChanged(object sender,EventArgs e){if(_syncing)return;if(Read(CenterXBox.Text,out double x))_centerX=x;if(Read(CenterYBox.Text,out double y))_centerY=y;if(Read(ScaleBox.Text,out double scale)&&scale is>=.05 and<=40)_scale=scale;UpdateTransform();Schedule();}
    private void Schedule(){if(!IsLoaded)return;_cts?.Cancel();_timer.Stop();_timer.Start();}private void Render_OnClick(object sender,RoutedEventArgs e){_timer.Stop();_cts?.Cancel();_=RenderAsync();}private void Cancel_OnClick(object sender,RoutedEventArgs e)=>_cts?.Cancel();
    private async Task RenderAsync(){if(_rendering){Schedule();return;}IfsState state;try{state=CaptureState("preview");}catch(Exception ex){StatusText.Text=ex.Message;return;}_cts?.Dispose();_cts=new();CancellationToken token=_cts.Token;_rendering=true;CancelButton.IsEnabled=true;RenderBadge.Visibility=Visibility.Visible;var watch=Stopwatch.StartNew();try{RenderSurfaceMetrics surface=RenderSurfaceMetrics.Measure(CanvasHost);DpiScale dpi=surface.Dpi;int width=surface.PixelWidth,height=surface.PixelHeight;var bitmap=new WriteableBitmap(width,height,dpi.PixelsPerInchX,dpi.PixelsPerInchY,PixelFormats.Bgra32,null);var renderer=new IfsRenderer(state,width,height);int generationBatch=Math.Clamp(state.Iterations/20,5000,100000);while(renderer.GeneratedPoints<state.Iterations&&!token.IsCancellationRequested){await Task.Run(()=>renderer.Generate(Math.Min(generationBatch,state.Iterations-renderer.GeneratedPoints),token));int p=(int)(renderer.GeneratedPoints*50d/state.Iterations);ProgressBar.Value=p;ProgressText.Text=$"Построение орбиты: {p*2}%";RenderBadgeText.Text=$"Орбита: {renderer.GeneratedPoints:N0} / {state.Iterations:N0}";}if(token.IsCancellationRequested){CurrentImage.Source=null;StatusText.Text="Рендер отменён";return;}CurrentImage.Source=bitmap;int plotBatch=Math.Clamp(state.Iterations/24,4000,100000);while(renderer.PlottedPoints<state.Iterations&&!token.IsCancellationRequested){await Task.Run(()=>renderer.Plot(Math.Min(plotBatch,state.Iterations-renderer.PlottedPoints),token));byte[] frame=renderer.CreateFrame();bitmap.WritePixels(new Int32Rect(0,0,width,height),frame,width*4,0);int p=50+(int)(renderer.PlottedPoints*50d/state.Iterations);ProgressBar.Value=p;ProgressText.Text=$"Вывод точек: {(p-50)*2}%";RenderBadgeText.Text=$"Точки: {renderer.PlottedPoints:N0} / {state.Iterations:N0}";}if(token.IsCancellationRequested){CurrentImage.Source=null;StatusText.Text="Рендер отменён";return;}BitmapSource done=bitmap.Clone();done.Freeze();StableImage.Source=done;CurrentImage.Source=null;_renderedCenterX=state.CenterX;_renderedCenterY=state.CenterY;_renderedScale=state.Scale;_hasFrame=true;UpdateTransform();ProgressBar.Value=100;ProgressText.Text="Рендер завершён";StatusText.Text=$"Готово за {watch.Elapsed.TotalSeconds:F3} сек.";}catch(OperationCanceledException){CurrentImage.Source=null;StatusText.Text="Рендер отменён";}catch(Exception ex){CurrentImage.Source=null;MessageBox.Show(this,ex.Message,"IFS",MessageBoxButton.OK,MessageBoxImage.Error);}finally{_rendering=false;CancelButton.IsEnabled=false;RenderBadge.Visibility=Visibility.Collapsed;}}
    private void Transforms_OnClick(object sender,RoutedEventArgs e){var editor=new IfsTransformEditorWindow(_transforms){Owner=this};editor.TransformsApplied+=ApplyTransforms;editor.ShowDialog();}private void ApplyTransforms(IReadOnlyList<IfsAffineTransform> transforms){_presetId=null;_transforms.Clear();_transforms.AddRange(transforms.Select(t=>t.Clone()));_syncing=true;PresetBox.SelectedItem=null;_syncing=false;Schedule();}
    private void FractalColor_OnClick(object sender,RoutedEventArgs e){if(_picker.TrySelectColor(this,_fractalColor,out Color color)){_fractalColor=color;UpdateSwatches();Schedule();}}private void BackgroundColor_OnClick(object sender,RoutedEventArgs e){if(_picker.TrySelectColor(this,_backgroundColor,out Color color)){_backgroundColor=color;UpdateSwatches();Schedule();}}private void UpdateSwatches(){FractalColorSwatch.Background=new SolidColorBrush(_fractalColor);BackgroundColorSwatch.Background=new SolidColorBrush(_backgroundColor);CanvasHost.Background=new SolidColorBrush(_backgroundColor);}
    private void Reset_OnClick(object sender,RoutedEventArgs e){_centerX=_centerY=0;_scale=2.4;SyncViewport();UpdateTransform();Schedule();}private void Saves_OnClick(object sender,RoutedEventArgs e)=>SaveManagerWindow.Open(this,SaveManagerConfigurations.ForIfs(this,_saves));
    private void Export_OnClick(object sender,RoutedEventArgs e){RenderSurfaceMetrics surface=RenderSurfaceMetrics.Measure(CanvasHost);int sourceW=surface.PixelWidth,sourceH=surface.PixelHeight;_cts?.Cancel();try{_=CaptureState("export");}catch(Exception ex){MessageBox.Show(this,ex.Message,"Параметры экспорта",MessageBoxButton.OK,MessageBoxImage.Warning);return;}ImageExportManagerWindow.Open(this,new ImageExportConfiguration{FileNamePrefix="ifs",InitialWidth=sourceW,InitialHeight=sourceH,MaxSsaaFactor=4,HasNativeSsaa=false,RenderAsync=(request,token,progress)=>{IfsState state=CaptureState("export");double factor=Math.Max(1,request.Width*(double)request.Height/(sourceW*(double)sourceH));state.Iterations=(int)Math.Min(int.MaxValue,Math.Ceiling(state.Iterations*factor));return RenderBitmapAsync(state,request.Width,request.Height,token,progress);}});}
    private static async Task<BitmapSource> RenderBitmapAsync(IfsState state,int width,int height,CancellationToken token,IProgress<int>? progress){var renderer=new IfsRenderer(state,width,height);while(renderer.GeneratedPoints<state.Iterations&&!token.IsCancellationRequested){await Task.Run(()=>renderer.Generate(Math.Min(100000,state.Iterations-renderer.GeneratedPoints),token));progress?.Report((int)(renderer.GeneratedPoints*50d/state.Iterations));}while(renderer.PlottedPoints<state.Iterations&&!token.IsCancellationRequested){await Task.Run(()=>renderer.Plot(Math.Min(100000,state.Iterations-renderer.PlottedPoints),token));progress?.Report(50+(int)(renderer.PlottedPoints*50d/state.Iterations));}byte[] pixels=renderer.CreateFrame();BitmapSource bitmap=BitmapSource.Create(width,height,96,96,PixelFormats.Bgra32,null,pixels,width*4);bitmap.Freeze();return bitmap;}
    private void CanvasHost_OnSizeChanged(object sender,SizeChangedEventArgs e){UpdateTransform();Schedule();}private void CanvasHost_OnMouseWheel(object sender,MouseWheelEventArgs e){Point p=e.GetPosition(CanvasHost);var before=ScreenToWorld(p);_scale=Math.Clamp(_scale*(e.Delta>0?.86:1.17),.05,40);var after=ScreenToWorld(p);_centerX+=before.X-after.X;_centerY+=before.Y-after.Y;SyncViewport();UpdateTransform();Schedule();}private void CanvasHost_OnMouseLeftButtonDown(object sender,MouseButtonEventArgs e){_cts?.Cancel();_panning=true;_panStart=e.GetPosition(CanvasHost);CanvasHost.CaptureMouse();}private void CanvasHost_OnMouseMove(object sender,MouseEventArgs e){if(!_panning)return;Point p=e.GetPosition(CanvasHost);var a=ScreenToWorld(_panStart);var b=ScreenToWorld(p);_centerX+=a.X-b.X;_centerY+=a.Y-b.Y;_panStart=p;SyncViewport();UpdateTransform();}private void CanvasHost_OnMouseLeftButtonUp(object sender,MouseButtonEventArgs e){if(!_panning)return;_panning=false;CanvasHost.ReleaseMouseCapture();Schedule();}
    private (double X,double Y) ScreenToWorld(Point p){double w=Math.Max(1,CanvasHost.ActualWidth),h=Math.Max(1,CanvasHost.ActualHeight),worldH=_scale*h/w;return(_centerX+(p.X/w-.5)*_scale,_centerY-(p.Y/h-.5)*worldH);}private void SyncViewport(){_syncing=true;CenterXBox.Text=F(_centerX);CenterYBox.Text=F(_centerY);ScaleBox.Text=F(_scale);_syncing=false;}private void UpdateTransform(){if(!_hasFrame||CanvasHost.ActualWidth<=0)return;double w=CanvasHost.ActualWidth,h=CanvasHost.ActualHeight,worldH=_scale*h/w;_imageScale.ScaleX=_imageScale.ScaleY=_renderedScale/_scale;_translation.X=(_renderedCenterX-_centerX)/_scale*w;_translation.Y=(_centerY-_renderedCenterY)/worldH*h;}
    private void Toggle_OnClick(object sender,RoutedEventArgs e)=>FractalControlPanel.Toggle(ref _controls,ControlsColumn,ControlsHost,ToggleButton,300,Schedule);private void Window_OnKeyDown(object sender,KeyEventArgs e){if(e.Key==Key.F11||e.Key==Key.Escape&&_fullscreen)ToggleFull();}private void ToggleFull(){if(!_fullscreen){_oldStyle=WindowStyle;_oldState=WindowState;WindowStyle=WindowStyle.None;WindowState=WindowState.Maximized;}else{WindowStyle=_oldStyle;WindowState=_oldState;}_fullscreen=!_fullscreen;}private void Window_OnClosing(object? sender,System.ComponentModel.CancelEventArgs e){_timer.Stop();_cts?.Cancel();_cts?.Dispose();}private static bool Read(string text,out double value)=>double.TryParse(text,NumberStyles.Float,CultureInfo.InvariantCulture,out value)||double.TryParse(text,NumberStyles.Float,CultureInfo.CurrentCulture,out value);private static string F(double value)=>value.ToString("G15",CultureInfo.InvariantCulture);
}
