//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FractalExplorer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1920")]
        public decimal SaveForm_Width {
            get {
                return ((decimal)(this["SaveForm_Width"]));
            }
            set {
                this["SaveForm_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1080")]
        public decimal SaveForm_Height {
            get {
                return ((decimal)(this["SaveForm_Height"]));
            }
            set {
                this["SaveForm_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SaveForm_FormatIndex {
            get {
                return ((int)(this["SaveForm_FormatIndex"]));
            }
            set {
                this["SaveForm_FormatIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SaveForm_SsaaIndex {
            get {
                return ((int)(this["SaveForm_SsaaIndex"]));
            }
            set {
                this["SaveForm_SsaaIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("95")]
        public int SaveForm_JpgQuality {
            get {
                return ((int)(this["SaveForm_JpgQuality"]));
            }
            set {
                this["SaveForm_JpgQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveForm_ApplyBicubic {
            get {
                return ((bool)(this["SaveForm_ApplyBicubic"]));
            }
            set {
                this["SaveForm_ApplyBicubic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SaveForm_BicubicFactorIndex {
            get {
                return ((int)(this["SaveForm_BicubicFactorIndex"]));
            }
            set {
                this["SaveForm_BicubicFactorIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveForm_ApplyLanczos {
            get {
                return ((bool)(this["SaveForm_ApplyLanczos"]));
            }
            set {
                this["SaveForm_ApplyLanczos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SaveForm_LanczosFactorIndex {
            get {
                return ((int)(this["SaveForm_LanczosFactorIndex"]));
            }
            set {
                this["SaveForm_LanczosFactorIndex"] = value;
            }
        }
    }
}
